### ISSUE TITLE
test4

### ISSUE THREAD

**Issue by TomoyaHaeiwa** [shiftware-test/shiftware-test#5]
### ユーザ影響
NTPが既にインストールされているターゲットに対し、NTPのSlewモードのみの変更が行えない。

### 課題
NTPのSlewモードの設定をする以下のコードにおいて、処理は/etc/sysconfig/ntpdに対して一回行えばいいのにもかかわらず、無駄にbase_advanced.timeserverオブジェクトでループを回している。このため、base_advanced.timeserverが定義されていないとタスクがスキップされてしまう。

```
- name: 1-0001-09_NtpSlew(set slew enable)
  lineinfile:
    dest: '/etc/sysconfig/ntpd'
    regexp: "^OPTIONS*"
    line: "OPTIONS=\"-x -u ntp:ntp -p /var/run/ntpd.pid -g\""
  notify: ntpd_restart
  with_items: base_advanced.timeserver  ◆ここ
  when:
    - base_advanced.ntp_option is defined
    - base_advanced.ntp_option.slew == true

- name: 1-0001-09_NtpSlew(set slew disable)
  lineinfile:
    dest: '/etc/sysconfig/ntpd'
    regexp: "^OPTIONS=*"
    line: "OPTIONS=\"-u ntp:ntp -p /var/run/ntpd.pid -g\""
  notify: ntpd_restart
  with_items: base_advanced.timeserver  ◆ここ
  when:
    - base_advanced.ntp_option is defined
    - base_advanced.ntp_option.slew == false
```
